SELECT DISTINCT CITY
FROM STATION
WHERE NOT CITY LIKE '%A' AND NOT CITY LIKE '%E' AND NOT CITY LIKE '%I' AND NOT CITY LIKE '%O' AND NOT CITY LIKE '%U' AND NOT CITY LIKE 'A%' AND NOT CITY LIKE 'E%' AND NOT CITY LIKE 'I%' AND NOT CITY LIKE 'O%' AND NOT CITY LIKE 'U%'

-- FUNNY QUERY IN MYSQL X2
